[package]
name = "vaults"
version = "0.5.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
testutils = []

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
proptest = "1.0.0"
