name: Build and Release  # name it whatever you like
on:
  workflow_dispatch:

permissions: # required permissions for the workflow
  id-token: write
  contents: write
  attestations: write

jobs:
  release-router-contract:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}          # use git tag as unique release name
      relative_path: '["contracts/locking-pool"]'  # relative path to your really awesome contract
      package: 'locking-pool'                # package name to build
      make_target: 'build'             # make target to invoke
    secrets: # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }}    # don't modify this line