name: Build and Release the Vaults contract
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Unique release name'
        required: true
        type: string

jobs:
  release-vaults-contract:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@4d0117fd348fb90cc36e2cd8c774f822802752af
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Vaults contract'
      relative_path: '["contracts/vaults"]'
      package: 'vaults'
      make_target: 'build-vaults'
    secrets: # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.RELEASE_TOKEN }}