[package]
name = "vaults"
version = "0.2.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }

[dependencies.num-integer]
version = "0.1.36"
default-features = false

[dev_dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
